### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by Tinuz** [jangalinski/dropwizard-vaadin#2]
Hi,

Let me first say, great work on this! I am setting up a demo app based upon your project. I was wondering if you could explain to me how I could add a custom theme? Is this even possible?

**Comment by jangalinski** [comment]
Thanks for the feedback. Unfortunately, I have no idea ... I switched to using Spring-Boot for my projects a while ago. Here's how to do this with spring: http://www.sothawo.com/2015/06/custom-theme-for-a-vaadin-spring-boot-application/   If you want to adapt this for dropwizard ... I'd be glad to accept your PR.

**Comment by Tinuz** [comment]
Tnx for the quick reply! I will try to add custom theme based on the spring sample. Will keep you posted.

**Comment by jangalinski** [comment]
see above: not actively developed so I close issues.
