### ISSUE TITLE
Add-on support for widgetset 

### ISSUE THREAD

**Issue by pandaadb** [jangalinski/dropwizard-vaadin#3]
Hi,

I am setting up an integration of guice + vaadin + dw. So far so good, I "borrowed" some of your code and integrated with dropwizard-guicey and all works fine as long as I don't want to use a different widgetset. 

I know tried to add vaadin-charts. 

I am not sure how to achieve this. I am using the gradle-vaadin-plugin to compile my vaadinWidgetSet, however I keep seeing: 

Failed to load the widgetset: ./../VAADIN/widgetsets/org.pandaadb.MyWidgetSet/org.pandaadb.MyWidgetSet.nocache.js?1462985268015

I was wondering if you might have some pointers for me? 

Thanks! 

Artur

**Comment by jangalinski** [comment]
not actively developed so I close issues.
